### ISSUE TITLE
should this repo be archived and we link to https://github.com/IfcOpenBot/IfcOpenShell?

### ISSUE THREAD

**Issue by hugoledoux** [tudelft3d/ifc2citygml#10]
@aothms @kenohori what do you think?

**Comment by kenohori** [comment]
sure, fine by me!

**Comment by aothms** [comment]
My preference would be to link to from here to https://github.com/tudelft3d/esri_geobim

And make a note in the readme there that it is also embedded (as a git submodule) in IfcConvert with some instructions to get started.

**Comment by hugoledoux** [comment]
okay added a warning here, I'll let you guys add the readme in the esri_geobim repo
