### ISSUE TITLE
Lacking of file:SurfaceStyle.h

### ISSUE THREAD

**Issue by 9lovingly** [tudelft3d/ifc2citygml#3]
When I compile the source,I couldn't find the file: SurfaceStyle.h,Anyone can ask me where I can get it,I download:IfcOpenShell_CGAL,which doesn't contain it.

**Comment by grivy** [comment]
IfcOpenShell_CGAL did not exist at the time the code for this project was developed. Try:
https://github.com/IfcOpenShell/IfcOpenShell and probably an old version.
For more information see: https://github.com/tudelft3d/ifc2citygml/issues/2
