### ISSUE TITLE
Does the converter still works

### ISSUE THREAD

**Issue by berndhahnebach** [tudelft3d/ifc2citygml#7]
Just found this converter, but it is years old. Most users of IfcOpenShell use version 0.6.

Does anyone uses this converter ATM in 2020?

Is there another possibility to convert ifc to citygml available?

cheers bernd

**Comment by Moult** [comment]
+1 on this. I'd love to hear if there is a working version.

**Comment by bulutlar** [comment]
+1

**Comment by aothms** [comment]
@berndhahnebach @Moult I joined forces with these guys. We'll have some new version of this in the near future.

**Comment by Moult** [comment]
@aothms fantastic! Looking forward to it!

**Comment by petrik68** [comment]
We are  looking for the same topic and would like to see intermediate results if there is.

**Comment by aothms** [comment]
Intermediate results: 

E.g at a small test model Duplex Arch + installations at

![afbeelding](https://user-images.githubusercontent.com/1096535/97914090-9f781100-1d4f-11eb-93d4-80fb9990626d.png)

![afbeelding](https://user-images.githubusercontent.com/1096535/97914156-bc144900-1d4f-11eb-89fb-c634c56efaeb.png)

As a topologically valid and semantically ok representation of the facade in CityGML.

This completes in order of magnitude several minutes. Memory usage is rather high. A 100+mb model consumed 16G. There are still some open issues with mapping semantics of coplanar elements.

**Comment by berndhahnebach** [comment]
wow can't wait to get my hands on this too

**Comment by petrik68** [comment]
Looks promising,

Is the version available on git? or was this done with the old version?  

2 Nov 22:12:



Intermediate results:


E.g at a small test model Duplex Arch + installations at








As a topologically valid and semantically ok representation of the facade in CityGML.


This completes in order of magnitude several minutes. Memory usage is rather high. A 100+mb model consumed 16G. There are still some open issues with mapping semantics of coplanar elements.

**Comment by aothms** [comment]
This is with the version currently under development, not yet online.

**Comment by sensor-freak** [comment]
> This is with the version currently under development, not yet online.

Hi, can give us any news on the state of the project? Will there be a public version available for this project?

W'ed like to use the converters, but we don't want to spent much time in getting the old version running, if a newer version might be available soon. Can you give us any hints on when a new version will be ready?

Thank you!

**Comment by aothms** [comment]
I can provide an update next week when we meet with the team

**Comment by elyrank** [comment]
Is there an update on the subject? is there a new version?

**Comment by aothms** [comment]
Unfortunately there were some personnel changes on both sides of the pond. I no longer work at tudelft3d, but I don't mind putting the things online if you get an ok from @jstoter @kenohori or @hugoledoux

**Comment by hugoledoux** [comment]
all okay from my side to open-source it all 👍

**Comment by kenohori** [comment]
I think it's more of a question for @jstoter...

**Comment by jstoter** [comment]
Yes. Sounds good. Thanks!

**Comment by KaiH1628** [comment]
is there a new version now?

**Comment by kenohori** [comment]
sorry, but there's not a new version atm

**Comment by kenohori** [comment]
it is online: https://github.com/tudelft3d/esri_geobim

**Comment by aothms** [comment]
Thanks Ken, when I find the time I'd like to incorporate this into IfcConvert so that people benefit from the automated builds we provide there. For that I have a lengthy merge conflict though to get the IfcOpenShell+CGAL work we did back in sync with the original IfcOpenShell.

**Comment by kenohori** [comment]
Thanks to you, Thomas!

**Comment by berndhahnebach** [comment]
> ... I'd like to incorporate this into IfcConvert so that people benefit from the automated builds we provide there. For that I have a lengthy merge conflict though to get the IfcOpenShell+CGAL work we did back in sync with the original IfcOpenShell.

wow that would be great and very easy to use :-)

**Comment by aothms** [comment]
There's automated builds now of IfcConvert that include this functionality:

https://github.com/IfcOpenBot/IfcOpenShell/commit/48798ae07d08b43f69e0d6bbf7eb1861e16a2a83#comments

At everybody at tudelft3d thanks for the opportunity to work on this and the pleasant collaboration.

At everybody else: there's a massive task still at understanding the performance characteristics of this. Basically we only tried Duplex and massive airport models, where the former worked quite well, the latter not so much. Friendly advise to run with `-vvv` for to have a sense of what it's doing because otherwise it's not very talkative on what is going on. Happy testing!

**Comment by kenohori** [comment]
Thanks to you, @aothms! It has been a pleasure to work with you.
